# Homework 1

## Part I. HICP data from SDW

In [1]:
# import pandas (and other libraries you may want to use)
import pandas as pd

In [2]:
# import the data files you downloaded from SDW

df_0711 = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/071100.csv', skiprows=6, usecols=[0,1], header=None, index_col=0)
df_0712 = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/071200.csv', skiprows=6, usecols=[0,1], header=None, index_col=0)
df_0713 = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/071300.csv', skiprows=6, usecols=[0,1], header=None, index_col=0)
df_0721 = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/072100.csv', skiprows=6, usecols=[0,1], header=None, index_col=0)
df_0722 = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/072200.csv', skiprows=6, usecols=[0,1], header=None, index_col=0)
df_0723 = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/072300.csv', skiprows=6, usecols=[0,1], header=None, index_col=0)
df_0724 = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/072400.csv', skiprows=6, usecols=[0,1], header=None, index_col=0)
df_0731 = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/073100.csv', skiprows=6, usecols=[0,1], header=None, index_col=0)
df_0732 = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/073200.csv', skiprows=6, usecols=[0,1], header=None, index_col=0)
df_0733 = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/073300.csv', skiprows=6, usecols=[0,1], header=None, index_col=0)
df_0734 = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/073400.csv', skiprows=6, usecols=[0,1], header=None, index_col=0)
df_0735 = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/073500.csv', skiprows=6, usecols=[0,1], header=None, index_col=0)
df_0736 = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/073600.csv', skiprows=6, usecols=[0,1], header=None, index_col=0)

In [3]:
# Print as a list the codes of the subindices you downloaded.
# For example, if you download items from the __FOOD AND NON-ALCOHOLIC BEVERAGES__ category, 
# list all codes type `01XX00` you were able to download. 

list_subindices = ["071100","071200","071300","072100","072200","072300","072400","073100","073200","073300","073400","073500","073600"]
print(list_subindices)
type(list_subindices)

['071100', '071200', '071300', '072100', '072200', '072300', '072400', '073100', '073200', '073300', '073400', '073500', '073600']

list

In [4]:
# create a single dataframe combining data for all HICP subindices you downloaded
list_of_dfs = [df_0711, df_0712, df_0713, df_0721, df_0722, df_0723, df_0724, df_0731, df_0732, df_0733, df_0734, df_0735, df_0736]
df_merged = pd.concat(list_of_dfs, axis=1)

In [6]:
# make other changes to the dataframe - set datetime index, rename the columns (up to you, but shortning very names may be a good idea)
df_merged.index = pd.to_datetime(df_merged.index, format='%Y%b')
df_merged.columns = list_subindices

In [7]:
# print the type of the index of the dataframe

type(df_merged.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [8]:
# print the data types of the columns in the dataframe
df_merged.dtypes

071100    float64
071200    float64
071300    float64
072100    float64
072200    float64
072300    float64
072400    float64
073100    float64
073200    float64
073300    float64
073400    float64
073500    float64
073600    float64
dtype: object

In [9]:
# save as a csv file under the name of the item group
df_merged.to_csv(f'data/TRANSPORT_070000.csv', index=True)

In [10]:
# compute and print the means and standard deviations for each series for the full period

df_merged.apply(['mean','std'])

,071100,071200,071300,072100,072200,072300,072400,073100,073200,073300,073400,073500,073600
mean,0.948667,1.434694,1.267347,0.808000,3.314667,2.700667,1.748000,2.126333,2.358333,2.317333,2.814333,2.767667,1.443000
std,0.829211,1.112720,1.870092,1.018263,9.883911,0.832412,0.724878,1.723148,0.882853,4.802790,3.839257,1.132902,1.159886

In [11]:
# compute and print the means and standard deviations for each calendar month for each series
df_merged.groupby(df_merged.index.month).agg(['mean','std'])

   071100           071200           071300           072100           072200  \
     mean       std   mean       std   mean       std   mean       std   mean
0
1   0.908  0.635033  1.300  0.244949  0.800  1.471960  0.784  1.030647  2.956
2   0.900  0.660808  1.300  0.216025  0.800  1.407125  0.780  1.008299  3.056
3   0.904  0.688283  1.250  0.369685  0.875  1.645955  0.788  0.970532  3.240
4   0.912  0.721295  1.275  0.340343  0.950  1.644182  0.784  0.966816  3.136
5   0.920  0.750555  1.150  0.369685  1.075  1.685972  0.796  1.004772  3.260
6   0.912  0.807940  1.225  0.537742  1.125  1.374470  0.788  0.982056  3.304
7   0.940  0.875119  1.300  1.267544  1.125  1.846393  0.792  1.006197  3.404
8   0.952  0.875176  1.375  1.443087  1.325  2.239606  0.796  1.027732  3.324
9   0.968  0.943274  1.675  1.936276  1.625  2.696139  0.808  1.059843  3.408
10  0.980  0.976388  1.675  1.936276  1.725  2.675039  0.844  1.130295  3.556
11  1.032  0.992354  1.800  1.930458  1.950  2.718455  0.864  1.126529  3.632
12  1.056  1.061084  1.800  1.557241  1.720  2.595573  0.872  1.112250  3.500

               ... 073200           073300           073400           073500  \
          std  ...   mean       std   mean       std   mean       std   mean
0              ...
1    9.742607  ...  2.332  0.968986  1.952  3.885349  2.736  3.393484  2.800
2    9.707732  ...  2.344  0.903272  1.956  3.524211  2.860  3.571181  2.812
3   10.224725  ...  2.312  0.970532  2.196  3.722620  2.812  3.641465  2.788
4    9.738792  ...  2.244  1.108708  2.236  5.324619  2.812  4.849942  2.776
5   10.703543  ...  2.420  0.918332  2.064  3.617075  2.764  4.500637  2.784
6   10.050103  ...  2.376  0.912999  2.204  4.049329  2.696  4.401560  2.780
7   10.120091  ...  2.392  0.771319  2.432  4.094887  2.860  3.915674  2.752
8    9.268822  ...  2.368  0.783539  2.928  5.912876  3.164  5.075667  2.740
9   10.311924  ...  2.332  0.847408  2.308  5.572321  2.644  3.614448  2.752
10  10.408453  ...  2.356  0.848076  2.416  5.987047  2.832  2.872966  2.752
11  10.493757  ...  2.428  0.834925  2.400  5.675165  2.760  3.250128  2.740
12   9.968701  ...  2.396  0.857069  2.716  6.030940  2.832  3.128594  2.736

             073600
         std   mean       std
0
1   1.263922  1.468  1.177469
2   1.154455  1.444  1.074740
3   1.131489  1.452  1.055194
4   1.115527  1.448  1.032844
5   1.081157  1.448  1.118079
6   1.180748  1.444  1.197943
7   1.178672  1.436  1.238574
8   1.180748  1.424  1.313799
9   1.131783  1.444  1.284874
10  1.132887  1.444  1.165862
11  1.140175  1.432  1.347133
12  1.147417  1.432  1.125729

[12 rows x 26 columns]

In [12]:
# redo the above for the period between January 2017 and December 2021
print(df_merged.loc['2017-01':'2021-12',:].apply(['mean','std']))
df_merged['month']=df_merged.index.month
print(df_merged.loc['2017-01':'2021-12',:].groupby('month').agg(['mean','std']))
df_merged.drop(['month'], axis=1, inplace=True)

        071100    071200    071300    072100     072200    072300    072400  \
mean  1.456667  1.434694  1.267347  0.645000   4.688333  2.411667  1.690000
std   0.983657  1.112720  1.870092  0.835935  11.310009  0.406344  1.176853

        073100    073200    073300    073400    073500   073600
mean  0.458333  1.231667  1.928333  1.945000  1.246667  1.61500
std   2.364662  0.807904  7.262397  3.572988  0.448526  0.56892
      071100           071200           071300           072100            \
        mean       std   mean       std   mean       std   mean       std
month
1       1.14  0.403733  1.300  0.244949  0.800  1.471960   0.40  0.793725
2       1.14  0.391152  1.300  0.216025  0.800  1.407125   0.42  0.725948
3       1.24  0.492950  1.250  0.369685  0.875  1.645955   0.46  0.753658
4       1.30  0.400000  1.275  0.340343  0.950  1.644182   0.46  0.541295
5       1.32  0.438178  1.150  0.369685  1.075  1.685972   0.52  0.460435
6       1.38  0.634035  1.225  0.537742  1.125  1.374470   0.52  0.476445
7       1.46  1.057355  1.300  1.267544  1.125  1.846393   0.60  0.612372
8       1.48  1.040192  1.375  1.443087  1.325  2.239606   0.70  0.724569
9       1.58  1.263725  1.675  1.936276  1.625  2.696139   0.72  0.825833
10      1.70  1.483240  1.675  1.936276  1.725  2.675039   0.90  1.298075
11      1.82  1.642255  1.800  1.930458  1.950  2.718455   1.00  1.403567
12      1.92  1.834939  1.800  1.557241  1.720  2.595573   1.04  1.379493

      072200             ... 073200           073300            073400  \
        mean        std  ...   mean       std   mean        std   mean
month                    ...
1       2.94   7.937443  ...   0.92  0.975705   1.52   3.897050   1.90
2       3.94   7.316283  ...   1.02  0.852643   1.88   4.803853   2.44
3       4.40   6.822390  ...   0.94  0.859069   1.94   4.157884   2.26
4       4.38  11.865791  ...   0.70  1.115796   2.10  10.077946   2.86
5       4.32  14.650495  ...   1.56  0.912688   1.08   4.957520   2.62
6       3.84  12.885767  ...   1.36  0.730068   1.30   5.349299   2.04
7       4.60  12.191185  ...   1.48  0.496991   0.34   4.645213   0.82
8       5.12  12.164169  ...   1.30  0.504975   1.54   9.223232   1.46
9       5.04  13.150399  ...   1.16  0.545894   2.18   9.865952   1.92
10      5.86  15.793290  ...   1.26  0.723187   2.36  11.272001   1.74
11      6.64  17.170411  ...   1.62  1.207063   3.62  10.899174   1.72
12      5.18  13.245641  ...   1.46  0.826438   3.28  10.327246   1.56

                073500           073600
            std   mean       std   mean       std
month
1      1.752142   1.22  0.697854   1.64  0.517687
2      3.981583   1.26  0.610737   1.66  0.665582
3      3.277652   1.22  0.521536   1.64  0.585662
4      7.287867   1.24  0.230217   1.56  0.654217
5      5.544096   1.26  0.378153   1.58  0.739594
6      4.815392   1.26  0.279285   1.56  0.947629
7      3.744596   1.28  0.342053   1.56  0.680441
8      3.404115   1.22  0.334664   1.60  0.600000
9      2.006739   1.26  0.497996   1.72  0.476445
10     1.851486   1.26  0.598331   1.58  0.567450
11     2.090933   1.24  0.602495   1.60  0.489898
12     3.150079   1.24  0.598331   1.68  0.443847

[12 rows x 26 columns]

## Part II. GDP data from EUROSTAT

In [13]:
# import the data files you downloaded from EUROSTAT

df_gdp = pd.read_csv (r'C:/Users/danie/Documents/FEP/Doutoramento/Econometria_II/homeworks/econ108-hw1/data/gdp_data.csv', usecols=[7,8])

In [14]:
# create a dataframe with a datetime index matching the timing of the series you downloaded

df_gdp['date'] = pd.PeriodIndex(df_gdp['TIME_PERIOD'], freq='Q').to_timestamp()
df_gdp.set_index('date',inplace=True)
df_gdp.drop(['TIME_PERIOD'], axis=1, inplace=True)
df_gdp.rename(columns={"OBS_VALUE": "GDP"}, inplace=True)

In [15]:
# save as a csv file under the name "Real-GDP-EA.csv"

df_gdp.to_csv(f'data/Real-GDP-EA.csv', index=True)

## PART III Combine GDP and inflation data

In [16]:
# create a new datafame containing the GDP data and the inflation indices from the first task.
merged_gdp_infl=pd.merge(df_merged, df_gdp, left_index=True, right_index=True, how='outer')

In [17]:
#save as a csv file named "merged-GDP-inflation.csv"

merged_gdp_infl.to_csv(f'data/merged-GDP-inflation.csv', index=True)